#ifndef __CNN_DATATYPE_H__
#define __CNN_DATATYPE_H__

#include "constant.hpp"
#include "ac_fixed.hpp"

/********** CNN WEIGHT DATATYPE DEFINITION ************/


#define KERNEL_CONVLAYER1_WEIGHT_DATA_WIDTH 8
#define KERNEL_CONVLAYER1_WEIGHT_DATA_INT_WIDTH 2

#define KERNEL_CONVLAYER2_WEIGHT_DATA_WIDTH 8
#define KERNEL_CONVLAYER2_WEIGHT_DATA_INT_WIDTH 1

#define KERNEL_CONVLAYER3_WEIGHT_DATA_WIDTH 8
#define KERNEL_CONVLAYER3_WEIGHT_DATA_INT_WIDTH 1

#define PERCEPTRON_WEIGHT_DATA_WIDTH 8
#define PERCEPTRON_WEIGHT_DATA_INT_WIDTH 0

#define BIAS_CONVLAYER1_WEIGHT_DATA_WIDTH 16
#define BIAS_CONVLAYER1_WEIGHT_DATA_INT_WIDTH 2

#define BIAS_CONVLAYER2_WEIGHT_DATA_WIDTH 16
#define BIAS_CONVLAYER2_WEIGHT_DATA_INT_WIDTH 2

#define BIAS_CONVLAYER3_WEIGHT_DATA_WIDTH 16
#define BIAS_CONVLAYER3_WEIGHT_DATA_INT_WIDTH 2

#define BIAS_PERCEPTRON_WEIGHT_DATA_WIDTH 8
#define BIAS_PERCEPTRON_WEIGHT_DATA_INT_WIDTH 2

/******* image normalization datatype ************/

#define IMAGE_DATA_WIDTH 8
#define IMAGE_DATA_INT_WIDTH 2

/********* INTERMEDIARY RESULTS DATATYPE *********/

#define RESHAPE_DATA_WIDTH 16
#define RESHAPE_DATA_INT_WIDTH 8

#define PERCEPTRON_INTERN_PROD_DATA_WIDTH 16
#define PERCEPTRON_INTERN_PROD_DATA_INT_WIDTH 8

#define PERCEPTRON_INTERN_SUM_DATA_WIDTH 16
#define PERCEPTRON_INTERN_SUM_DATA_INT_WIDTH 8

#define PERCEPTRON_OUTPUT_DATA_WIDTH 16
#define PERCEPTRON_OUTPUT_DATA_INT_WIDTH 8

#define MAXPOOL_LAYER1_WEIGHT_DATA_WIDTH 16
#define MAXPOOL_LAYER1_WEIGHT_DATA_INT_WIDTH 2

#define MAXPOOL_LAYER2_WEIGHT_DATA_WIDTH 16
#define MAXPOOL_LAYER2_WEIGHT_DATA_INT_WIDTH 2

#define MAXPOOL_LAYER3_WEIGHT_DATA_WIDTH 16
#define MAXPOOL_LAYER3_WEIGHT_DATA_INT_WIDTH 2

/******** define cnn datatype for fixed point **************/

typedef ac_fixed<KERNEL_CONVLAYER1_WEIGHT_DATA_WIDTH,
  KERNEL_CONVLAYER1_WEIGHT_DATA_INT_WIDTH,true,AC_RND_INF,AC_SAT> kernelLayer1_weightDataType;
typedef ac_fixed<KERNEL_CONVLAYER2_WEIGHT_DATA_WIDTH,
  KERNEL_CONVLAYER2_WEIGHT_DATA_INT_WIDTH,true,AC_RND_INF,AC_SAT> kernelLayer2_weightDataType;
typedef ac_fixed<KERNEL_CONVLAYER3_WEIGHT_DATA_WIDTH,
  KERNEL_CONVLAYER3_WEIGHT_DATA_INT_WIDTH,true,AC_RND_INF,AC_SAT> kernelLayer3_weightDataType;
typedef ac_fixed<PERCEPTRON_WEIGHT_DATA_WIDTH,
  PERCEPTRON_WEIGHT_DATA_INT_WIDTH,true,AC_RND_INF,AC_SAT> fcLayer_weightDataType;
typedef ac_fixed<BIAS_CONVLAYER1_WEIGHT_DATA_WIDTH,
  BIAS_CONVLAYER1_WEIGHT_DATA_INT_WIDTH,true,AC_RND_INF,AC_SAT> biasLayer1_weightDataType;
typedef ac_fixed<BIAS_CONVLAYER2_WEIGHT_DATA_WIDTH,
  BIAS_CONVLAYER2_WEIGHT_DATA_INT_WIDTH,true,AC_RND_INF,AC_SAT> biasLayer2_weightDataType;
typedef ac_fixed<BIAS_CONVLAYER3_WEIGHT_DATA_WIDTH,
  BIAS_CONVLAYER3_WEIGHT_DATA_INT_WIDTH,true,AC_RND_INF,AC_SAT> biasLayer3_weightDataType;
typedef ac_fixed<BIAS_PERCEPTRON_WEIGHT_DATA_WIDTH,
  BIAS_PERCEPTRON_WEIGHT_DATA_INT_WIDTH,true,AC_RND_INF,AC_SAT> biasfcLayer_weightDataType;

typedef ac_fixed<IMAGE_DATA_WIDTH,IMAGE_DATA_INT_WIDTH,true,
  AC_RND_INF,AC_SAT> imageNorm_dataType;

typedef ac_fixed<RESHAPE_DATA_WIDTH,RESHAPE_DATA_INT_WIDTH,false,
  AC_RND_INF,AC_SAT> inputVector_dataType;
typedef ac_fixed<PERCEPTRON_WEIGHT_DATA_WIDTH,PERCEPTRON_WEIGHT_DATA_INT_WIDTH,
  true,AC_RND_INF,AC_SAT> fcLayerVector_dataType;
typedef ac_fixed<PERCEPTRON_OUTPUT_DATA_WIDTH,PERCEPTRON_OUTPUT_DATA_INT_WIDTH,
  true,AC_RND_INF,AC_SAT> outPutValue_dataType;
typedef ac_fixed<PERCEPTRON_INTERN_PROD_DATA_WIDTH,PERCEPTRON_INTERN_PROD_DATA_INT_WIDTH,
  true,AC_RND_INF,AC_SAT> internalProduct_dataType;
typedef ac_fixed<PERCEPTRON_INTERN_SUM_DATA_WIDTH,PERCEPTRON_INTERN_SUM_DATA_INT_WIDTH,
  true,AC_RND_INF,AC_SAT> internalSum_dataType;

typedef ac_fixed<MAXPOOL_LAYER1_WEIGHT_DATA_WIDTH,MAXPOOL_LAYER1_WEIGHT_DATA_INT_WIDTH,
  false,AC_RND_INF,AC_SAT> poolingLayer1_DataType;
typedef ac_fixed<MAXPOOL_LAYER2_WEIGHT_DATA_WIDTH,MAXPOOL_LAYER2_WEIGHT_DATA_INT_WIDTH,
  false,AC_RND_INF,AC_SAT> poolingLayer2_DataType;
typedef ac_fixed<MAXPOOL_LAYER3_WEIGHT_DATA_WIDTH,MAXPOOL_LAYER3_WEIGHT_DATA_INT_WIDTH,
  false,AC_RND_INF,AC_SAT> poolingLayer3_DataType;

#else
typedef ac_fixed<KERNEL_CONVLAYER1_WEIGHT_DATA_WIDTH,
  KERNEL_CONVLAYER1_WEIGHT_DATA_INT_WIDTH,true,AC_RND_INF,AC_SAT> kernelLayer1_weightDataType;
typedef ac_fixed<KERNEL_CONVLAYER2_WEIGHT_DATA_WIDTH,
  KERNEL_CONVLAYER2_WEIGHT_DATA_INT_WIDTH,true,AC_RND_INF,AC_SAT> kernelLayer2_weightDataType;
typedef ac_fixed<KERNEL_CONVLAYER3_WEIGHT_DATA_WIDTH,
  KERNEL_CONVLAYER3_WEIGHT_DATA_INT_WIDTH,true,AC_RND_INF,AC_SAT> kernelLayer3_weightDataType;
typedef ac_fixed<PERCEPTRON_WEIGHT_DATA_WIDTH,
  PERCEPTRON_WEIGHT_DATA_INT_WIDTH,true,AC_RND_INF,AC_SAT> fcLayer_weightDataType;
typedef ac_fixed<BIAS_CONVLAYER1_WEIGHT_DATA_WIDTH,
  BIAS_CONVLAYER1_WEIGHT_DATA_INT_WIDTH,true,AC_RND_INF,AC_SAT> biasLayer1_weightDataType;
typedef ac_fixed<BIAS_CONVLAYER2_WEIGHT_DATA_WIDTH,
  BIAS_CONVLAYER2_WEIGHT_DATA_INT_WIDTH,true,AC_RND_INF,AC_SAT> biasLayer2_weightDataType;
typedef ac_fixed<BIAS_CONVLAYER3_WEIGHT_DATA_WIDTH,
  BIAS_CONVLAYER3_WEIGHT_DATA_INT_WIDTH,true,AC_RND_INF,AC_SAT> biasLayer3_weightDataType;
typedef ac_fixed<BIAS_PERCEPTRON_WEIGHT_DATA_WIDTH,
  BIAS_PERCEPTRON_WEIGHT_DATA_INT_WIDTH,true,AC_RND_INF,AC_SAT> biasfcLayer_weightDataType;

typedef ac_fixed<IMAGE_DATA_WIDTH,IMAGE_DATA_INT_WIDTH,true,
  AC_RND_INF,AC_SAT> imageNorm_dataType;

typedef ac_fixed<RESHAPE_DATA_WIDTH,RESHAPE_DATA_INT_WIDTH,false,
  AC_RND_INF,AC_SAT> inputVector_dataType;
typedef ac_fixed<PERCEPTRON_WEIGHT_DATA_WIDTH,PERCEPTRON_WEIGHT_DATA_INT_WIDTH,
  true,AC_RND_INF,AC_SAT> fcLayerVector_dataType;
typedef ac_fixed<PERCEPTRON_OUTPUT_DATA_WIDTH,PERCEPTRON_OUTPUT_DATA_INT_WIDTH,
  true,AC_RND_INF,AC_SAT> outPutValue_dataType;
typedef ac_fixed<PERCEPTRON_INTERN_PROD_DATA_WIDTH,PERCEPTRON_INTERN_PROD_DATA_INT_WIDTH,
  true,AC_RND_INF,AC_SAT> internalProduct_dataType;
typedef ac_fixed<PERCEPTRON_INTERN_SUM_DATA_WIDTH,PERCEPTRON_INTERN_SUM_DATA_INT_WIDTH,
  true,AC_RND_INF,AC_SAT> internalSum_dataType;

typedef ac_fixed<MAXPOOL_LAYER1_WEIGHT_DATA_WIDTH,MAXPOOL_LAYER1_WEIGHT_DATA_INT_WIDTH,
  false,AC_RND_INF,AC_SAT> poolingLayer1_DataType;
typedef ac_fixed<MAXPOOL_LAYER2_WEIGHT_DATA_WIDTH,MAXPOOL_LAYER2_WEIGHT_DATA_INT_WIDTH,
  false,AC_RND_INF,AC_SAT> poolingLayer2_DataType;
typedef ac_fixed<MAXPOOL_LAYER3_WEIGHT_DATA_WIDTH,MAXPOOL_LAYER3_WEIGHT_DATA_INT_WIDTH,
  false,AC_RND_INF,AC_SAT> poolingLayer3_DataType;


#endif
