#ifndef _CONVLAYER1CONSTANT_HPP_
#define _CONVLAYER1CONSTANT_HPP_

#define KERNEL_SIZE 9
#define KERNEL_SHAPE 3
#define IMG_SHAPE 24
#define IMG_SIZE (IMG_SHAPE*IMG_SHAPE)
#define IMG_CHANNEL_IN 3
#define IMG_CHANNEL_OUT 64

#endif
